# Generated by Django 5.2.6 on 2025-10-02 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grupoflashcard',
            unique_together={('nombre', 'tema')},
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.TextField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcard.grupoflashcard')),
            ],
            options={
                'unique_together': {('grupo', 'pregunta')},
            },
        ),
    ]
