# Generated by Django 5.2.6 on 2025-10-15 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_alter_grupoflashcard_unique_together_flashcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcard.grupoflashcard'),
        ),
    ]
