# Generated by Django 5.2.6 on 2025-10-15 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0003_alter_flashcard_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcard.grupoflashcard'),
            preserve_default=False,
        ),
    ]
