# Generated by Django 5.2.7 on 2025-10-15 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0004_alter_flashcard_grupo'),
        ('login', '0002_remove_cuenta_cuenta_balance_no_negativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='login.cuenta'),
        ),
        migrations.AddField(
            model_name='grupoflashcard',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_flashcard', to='login.cuenta'),
        ),
    ]
