# Generated by Django 5.2.7 on 2025-10-15 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_flashcard_cuenta_grupoflashcard_cuenta'),
        ('login', '0002_remove_cuenta_cuenta_balance_no_negativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='login.cuenta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grupoflashcard',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_flashcard', to='login.cuenta'),
        ),
    ]
