# Generated by Django 5.2.7 on 2025-10-15 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='cuenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='login.cuenta'),
            preserve_default=False,
        ),
    ]
