# Generated by Django 5.2.7 on 2025-10-16 02:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('sombrero', 'Sombrero'), ('ropa', 'Ropa'), ('libro', 'Libro')], default='none', max_length=20)),
                ('foto', models.ImageField(upload_to='fotos_mascotas/accesorios/')),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.IntegerField(default=100)),
                ('foto', models.ImageField(upload_to='fotos_mascotas/')),
                ('moneda', models.CharField(max_length=10)),
                ('mensajes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=['Hora de estudiar', '¡Sigue asi!', '¡Te estas superando a ti mismo', 'Tu falta de compromiso me deprime', '¡Eres sorprendente!'], editable=False, size=None)),
                ('monedas', models.IntegerField(default=10)),
                ('accesorios', models.ManyToManyField(blank=True, related_name='mascotas', to='mascota.accesorio')),
            ],
        ),
    ]
