# Generated by Django 5.2.7 on 2025-10-16 04:50

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_cuenta_cuenta_balance_no_negativo_and_more'),
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='accesorios',
            new_name='accesorios_comprados',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='moneda',
        ),
        migrations.AddField(
            model_name='mascota',
            name='cuenta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mascota', to='login.cuenta'),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='tipo',
            field=models.CharField(choices=[('tipo1', 'Tipo 1'), ('tipo2', 'Tipo 2'), ('tipo3', 'Tipo 3')], default='tipo1', max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='mensajes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
