# Generated by Django 5.2.7 on 2025-10-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_rename_accesorios_mascota_accesorios_comprados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='mensajes',
            field=models.CharField(max_length=100),
        ),
    ]
