# Generated by Django 5.2.7 on 2025-10-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cuenta',
            name='cuenta_balance_no_negativo',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='monedas',
        ),
    ]
