# Generated by Django 5.2.5 on 2025-08-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuración predetermianda', max_length=30)),
                ('work', models.IntegerField(default=25)),
                ('rest', models.IntegerField(default=5)),
            ],
        ),
    ]
