# Generated by Django 5.2.7 on 2025-10-16 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_remove_cuenta_cuenta_balance_no_negativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('work', 'Work'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], max_length=15)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=0)),
                ('was_successful', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_history', to='login.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='PomodoroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mi Temporizador Pomodoro', max_length=50)),
                ('work_time', models.IntegerField(default=25)),
                ('break_time', models.IntegerField(default=5)),
                ('long_break_time', models.IntegerField(default=15)),
                ('sessions_completed', models.IntegerField(default=0)),
                ('sessions_until_long_break', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_settings', to='login.cuenta')),
            ],
        ),
    ]
