# Generated by Django 5.2.6 on 2025-09-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Configuración predetermianda', max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=25)),
                ('seconds', models.IntegerField(default=0)),
                ('rest', models.IntegerField(default=5)),
                ('uuid', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Pomodoro',
        ),
    ]
