# Generated by Django 5.2.7 on 2025-10-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0003_pomodorohistory_pomodorosettings_delete_temporizador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomodorosettings',
            old_name='working_time',
            new_name='focus_time',
        ),
    ]
