# Generated by Django 5.2.7 on 2025-10-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0004_rename_working_time_pomodorosettings_focus_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomodorosettings',
            old_name='focus_time',
            new_name='work_time',
        ),
        migrations.AlterField(
            model_name='pomodorohistory',
            name='session_type',
            field=models.CharField(choices=[('work', 'Work'), ('short_break', 'Short Break'), ('long_break', 'Long Break')], max_length=15),
        ),
    ]
